### ISSUE TITLE
Dovecot autocreate plugin is deprecated

### ISSUE THREAD

**Issue by Snipees** [YunoHost/yunohost-config-dovecot#4]
Hello,

I having a lot of warning messages in '/var/log/mail.log' with this:
Warning: autocreate plugin is deprecated, use mailbox { auto } setting instead

Can I remove "autocreate" plugin from '/etc/dovecot/dovecot.conf' (protocol imap {}" block) without impact the mail services ?

[note: I'm on Debian GNU/Linux 8.1 (jessie)]

regards

**Comment by Kloadut** [comment]
Yes you can on Jessie (8.1)

A patch is already on his way: https://github.com/YunoHost/yunohost-config-dovecot/pull/3
