### ISSUE TITLE
Warning: autocreate plugin is deprecated,

### ISSUE THREAD

**Issue by JocelynDelalande** [YunoHost/yunohost-config-dovecot#7]
I'm getting a lot of those in my logs, maybe since jessie upgrade :

    Sep  6 06:37:49 yuno dovecot: imap(user): Warning: autocreate plugin is deprecated, use mailbox { auto } setting instead

**Comment by Kloadut** [comment]
Solved \o/

https://github.com/YunoHost/yunohost-config-dovecot/pull/3

**Comment by JocelynDelalande** [comment]
Sorry for duplicate.
